# Source language (using C since .NET and C# are not supported yet)
language: c

# Install dependencies needed to compile .NET and C#
install: sudo apt-get install mono-devel mono-gmcs

# Run the XBuild project file
script: xbuild Oxide.csproj /p:Configuration=Release

# Perform steps after compilation/test success
after_success:
  # Run deployment script
  - "./deploy.sh"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  # IRC notification
  irc:
    - "chat.freenode.net#rustoxide"
    - "irc.esper.net#rustoxide"

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
